spring:
  cloud:
    stream:
      bindings:
        input:
          destination: dataIn
          binder: nats
        output:
          destination: dataOut
          binder: nats

nats:
  spring:
    nats-url: nats://localhost:4222
    cluster-id: test-cluster
    client-id: spring-nats-processor-sample
